version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: hexagonal_db
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
